version: '2'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    ports:
    - 5500:5500
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tests
      - SPRING_DATASOURCE_USERNAME=Sylvain

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=Sylvain
      - POSTGRES_HOST_AUTH_METHOD=trust