server:
  port: ${PORT:5500}

spring:
  application:
    name: reit-app
  datasource:
    platform: org.hibernate.dialect.PostgreSQLDialect
    url: ${DB_URL:jdbc:postgresql://localhost:5432/tests2}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123}
    hikari:
      maximum-pool-size: ${MAX_POOL_SIZE:30}
      minimum-idle: ${INITIAL_DB_SIZE:10}

  jpa:
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
#    hibernate:
#      ddl-auto: create

  flyway:
    enabled: true
    baseline-on-migrate: true

management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true

  endpoints:
    web:
      exposure:
        include: "*"